#!/bin/bash
#
# Author: Michael Kepple
# Date: 24 Jan 2013
#
# This script performs syntax highlighting for the C language.
#
IFS='%'
sed 's/\(\&*[[:alpha:]]\+[[:alnum:]]*\(\[[[:alnum:]]*\]\)*\)\([ ,+;)]\+\)/\@\1\@\3/g' $1 |
awk '$0=gensub(/(@break@|@case@|@char@|@continue@|@default@|@do@|@double@|@else@|@entry@|@extern@|@float@|@for@|@goto@|@if@|@int@|@long@|@register@|@return@|@short@|@sizeof@|@static@|@struct@|@switch@|@typedef@|@union@|@unsigned@|@while@)/,"|\\1|","g")'
unset IFS

:'
===============================================================================
Test
===============================================================================
(student)~/5520/Lab1-1% hcindents lab01test.c
//
//  http://www.programmingsimplified.com/c/source-code/c-program-selection-sort
//

#include<stdio.h>
 
main()
{
   |@int@| @array[100]@, @n@, @c@, @d@, @position@, @swap@;
 
   printf("@Enter@ @number@ @of@ elements\n");
   scanf("%d", @&n@);
 
   printf("@Enter@ %@d@ integers\n", @n@);
 
   |@for@| ( @c@ = 0 ; @c@ < @n@ ; @c@++ )
      scanf("%d", @&array[c]@);
 
   |@for@| ( @c@ = 0 ; @c@ < ( @n@ - 1 ) ; @c@++ )
   {
      @position@ = @c@;
      
      |@for@| ( @d@ = @c@ + 1 ; @d@ < @n@ ; @d@++ )
      {
         |@if@| ( @array[position]@ > @array[d]@ )
            @position@ = @d@;
      }
      |@if@| ( @position@ != @c@ )
      {
         @swap@ = @array[c]@;
         @array[c]@ = @array[position]@;
         @array[position]@ = @swap@;
      }
   }
 
   printf("@Sorted@ @list@ @in@ @ascending@ order:\n");
 
   |@for@| ( @c@ = 0 ; @c@ < @n@ ; @c@++ )
      printf("%d\n", @array[c]@);
 
   |@return@| 0;
}

'
